print("Getting to know you!")
Name = input("What's your name?: ")
print("You are")
print(Name)
Food = input("What's your favourite foods?")
print("You're probably hungry for")
print(Food)
Music = input("What's your favourite music?")
print("and you're definitely getting your groove on to")
print(Music)
Live = input("Where do you live?")
print("living in the amazing")
print(Live)
